
jQuery(function(){function a(){var a=$("header").outerHeight(),b=$(".toolbar").outerHeight(),c=$(".page-header").outerHeight(),d=$("footer").outerHeight(),a=$(window).outerHeight()-(a+b+d);$(".body").css("minHeight",a-c);$(".sidebar").css("minHeight",a)}$("html").removeClass("no-js").addClass("js");$("body").removeClass("thumbnail error");$(".PageControls .BoxButtons").remove();$(".MessageList .Item").each(function(){$(this).find(".AuthorWrap .PhotoWrap").length||$(".AuthorWrap .Author").prepend("<a class='PhotoWrap' />")});
$.event.add(document,"ready",a);$.event.add(window,"resize",a)});var RecaptchaOptions={theme:"clean"};jQuery.fn.outerHTML=function(a){return a?this.before(a).remove():jQuery("<p>").append(this.eq(0).clone()).html()};
jQuery(function(){$(".Button").toggleClass("Button btn");$(".Button").livequery(function(){$(this).toggleClass("Button btn")});$(".BigButton").addClass("btn btn-block btn-large btn-primary").removeClass("BigButton");$(".ClearConversation").toggleClass("btn-primary btn-danger");$(".ButtonGroup").each(function(){$(this).addClass("btn-group");$(this).find(".Handle").each(function(){$(this).addClass("dropdown-toggle");$(this).find(".Sprite").toggleClass("Sprite SpDropdownHandle caret")})});$(".ButtonGroup.Profiles .dropdown-menu").livequery(function(){$(this).addClass("pull-right")});
$(".Active").addClass("active")});
jQuery(function(){$("#PagerAfter").remove();$("#PagerBefore").each(function(){$(this).addClass("btn-group");$(this).children().addClass("btn btn-mini");$(this).find(".Highlight").addClass("active");$(this).find("span").addClass("disabled");$(".CommentHeading").prepend(this)})});
jQuery(function(){$(".OptionsTitle").livequery(function(){$(this).toggleClass("OptionsTitle btn btn-mini").append(" <span class='caret'></span>")});$(".dropdown-menu ul li hr").livequery(function(){$(this).parent().addClass("divider");$(this).remove()});$(".MenuItems").livequery(function(){$(this).toggleClass("MenuItems dropdown-menu")});$(".FlyoutMenu").livequery(function(){$(this).addClass("dropdown-menu")});$(".ac_results").livequery(function(){$(this).find("ul").addClass("typeahead dropdown-menu")})});
jQuery(function(){$.fn.autogrow=function(){};$("textarea").livequery(function(){$(this).autosize({append:"\n"})});$(".Category select").each(function(){$(this).find("option").each(function(){var a=$.trim($(this).text());$(this).contents().replaceWith(a.replace(/(\u00a0)/g," "))});$(this).find("option[disabled]").each(function(){var a=$(this).text(),b=$(this).nextUntil("option[disabled]"),b=$("<option />").append($(b)).html();$(this).replaceWith($("<optgroup label='"+a+"'>"+b+"</optgroup>"))});$(this).find("option:empty").remove();
$(this).select2()});$(".CommentForm").find("textarea").attr("placeholder","Your comment goes here");$(".ActivityFormWrap .btn, .Profile form.Activity .btn").addClass("btn-primary").wrap("<div class='form-actions' />");$(".CommentFormWrap .Buttons").each(function(){$(this).toggleClass("Buttons form-actions");$(this).find("> a, > input").wrapAll("<span class='pull-right' />");$(this).find(".CommentButton").addClass("btn-primary");$(this).find(".PreviewButton, .WriteButton").addClass("btn");$(this).find(".WriteButton").hide();
$(this).find(".DraftButton").addClass("btn btn-info")})});
jQuery(function(){$(".navbar form").each(function(){$(this).addClass("navbar-search");$(this).find("input").addClass("search-query span2").attr("placeholder","enter your search terms");$(this).find("input[type=submit]").remove();$(this).show()})});

jQuery(function(){$("header").each(function(){var a=$(this).find(".brand").innerHeight();parseInt(a);var a=$(this).find(".MeBoxWrap"),b=$(this).find(".Username"),c=$(this).find(".PhotoWrap"),d=$(this).find(".MeMenu");b.prepend(c.find("img"));a.prepend(b.outerHTML());a.after("<li class='MeMenu'>"+d.html()+"</li>");$(this).find(".MeBox").remove()})});
jQuery(function(){$(".Popup").livequery(function(){$(this).find(".Body").addClass("modal")});$(".Popup .Content").livequery(function(){$(this).children("h1, h2").addClass("modal-header");$(this).children("*:not(.modal-header):not(.Entry)").addClass("modal-body")});$(".Popup .Content h1, .Popup .Content h2").livequery(function(){$(this).addClass("modal-header")});$(".Popup .Content").find("> *:not(.modal-header):not(.Entry)").livequery(function(){$(this).addClass("modal-body")});$(".Popup .Footer").livequery(function(){$(this).find("span").addClass("close")});
$(".Overlay").livequery(function(){$(this).fadeIn(150)})});
jQuery(function(){$(".BoxDiscussionFilter ul, .BoxCategories ul, .BoxProfileFilter ul, .BoxActivityFilter ul, .Profile .PanelInfo").removeClass("PanelInfo FilterMenu").addClass("nav nav-tabs nav-stacked");$(".PanelCategories .Heading").wrapInner("<a class='fish' />")});
jQuery(function(){});
jQuery(function(){var b=$(".page-header"),c=$(".CommentHeading"),a=$(".CommentForm h2.H"),d=$(".ProfileOptions"),e=d.find(".ProfileButtons"),f=$(".MessageList.Discussion .Options"),g=$(".body > h1, \t\t\t.PageTitle h1, \t\t\th1.H, \t\t\t.Profile.EditMode h2.H, \t\t\t.FormTitleWrapper > h1");e.removeClass("NavButton").addClass("btn");b.prepend(g.remove().text()).prepend(d.toggleClass("ProfileOptions pull-right").remove().outerHTML()).prepend(f.toggleClass("pull-right").remove().outerHTML());b.scrollToFixed({spacerClass:"scroll-spacer",
fixed:function(){var a=$(".main").width();$(this).addClass("fixed").css("width",a)},unfixed:function(){$(this).removeClass("fixed").width()}});c.scrollToFixed({spacerClass:"scroll-spacer",marginTop:59,limit:function(){if(a.length)return a.offset().top-c.outerHeight(!0)},fixed:function(){var a=$(".main").width();$(this).addClass("fixed").css("width",a)},unfixed:function(){$(this).removeClass("fixed").width()},preAbsolute:function(){$(this).addClass("absolute");a.length&&$(this).css("top",a.offset().top-
c.outerHeight(!0))},postAbsolute:function(){$(this).removeClass("absolute").css("z-index","1000")}});a.scrollToFixed({marginTop:b.outerHeight(),spacerClass:"scroll-spacer",fixed:function(){var a=$(".main").width();$(this).addClass("fixed").css("width",a)},unfixed:function(){$(this).removeClass("fixed").width()}});$(window).scroll(function(){var b=$(".main").width();$(".absolute").addClass("fixed").css("width",b).css("z-index",900).css("left",20);a.length&&$(".absolute").css("top",a.offset().top-142)})});
(function(a){var j={className:"autosizejs",append:"",callback:!1},k="hidden",g="fontFamily fontSize fontWeight fontStyle letterSpacing textTransform wordSpacing textIndent".split(" "),f=a('<textarea tabindex="-1" style="position:absolute; top:-9999px; left:-9999px; right:auto; bottom:auto; -moz-box-sizing:content-box; -webkit-box-sizing:content-box; box-sizing:content-box; word-wrap:break-word; height:0 !important; min-height:0 !important; overflow:hidden;"/>')[0];f.setAttribute("oninput","return");
a.isFunction(f.oninput)||"onpropertychange"in f?(a(f).css("lineHeight","99px"),"99px"===a(f).css("lineHeight")&&g.push("lineHeight"),a.fn.autosize=function(h){h=a.extend({},j,h||{});return this.each(function(){function d(){var a,d,g;l||(l=!0,e.value=b.value+h.append,e.style.overflowY=b.style.overflowY,g=parseInt(b.style.height,10),e.style.width=c.css("width"),e.scrollTop=0,e.scrollTop=9E4,a=e.scrollTop,d=k,a>i?(a=i,d="scroll"):a<f&&(a=f),a+=n,b.style.overflowY=d,g!==a&&(b.style.height=a+"px",q&&h.callback.call(b)),
setTimeout(function(){l=!1},1))}var b=this,c=a(b),e,f=c.height(),i=parseInt(c.css("maxHeight"),10),l,m=g.length,p,n=0,j=b.value,q=a.isFunction(h.callback);if("border-box"===c.css("box-sizing")||"border-box"===c.css("-moz-box-sizing")||"border-box"===c.css("-webkit-box-sizing"))n=c.outerHeight()-c.height();if(!c.data("mirror")&&!c.data("ismirror")){e=a('<textarea tabindex="-1" style="position:absolute; top:-9999px; left:-9999px; right:auto; bottom:auto; -moz-box-sizing:content-box; -webkit-box-sizing:content-box; box-sizing:content-box; word-wrap:break-word; height:0 !important; min-height:0 !important; overflow:hidden;"/>').data("ismirror",
!0).addClass(h.className)[0];p="none"===c.css("resize")?"none":"horizontal";c.data("mirror",a(e)).css({overflow:k,overflowY:k,wordWrap:"break-word",resize:p});for(i=i&&0<i?i:9E4;m--;)e.style[g[m]]=c.css(g[m]);a("body").append(e);"onpropertychange"in b?"oninput"in b?b.oninput=b.onkeyup=d:b.onpropertychange=d:(b.oninput=d,b.value="",b.value=j);a(window).resize(d);c.bind("autosize",d);d()}})}):a.fn.autosize=function(){return this}})(window.jQuery||window.Zepto);
(function(c){c.isScrollToFixed=function(d){return void 0!==c(d).data("ScrollToFixed")};c.ScrollToFixed=function(d,y){function u(){var a=b.options.limit;return!a?0:"function"===typeof a?a():a}function f(){return"fixed"===g}function k(){return"absolute"===g}function q(){f()||(e.css({display:a.css("display"),width:a.outerWidth(!0),height:a.outerHeight(!0),"float":a.css("float")}),a.css({width:a.width(),position:"fixed",top:-1==b.options.bottom?b.options.marginTop:"",bottom:-1==b.options.bottom?"":b.options.bottom}),
g="fixed")}function h(){if(f()||k())l=-1,e.css("display","none"),a.css({width:"",position:"",left:"",top:""}),g=null}function r(b){b!=l&&(a.css("left",i-b),l=b)}function s(){if(c.isScrollToFixed(a)){var m=n;n||(a.trigger("preUnfixed"),h(),a.trigger("unfixed"),l=-1,v=a.offset().top,i=a.offset().left,b.options.offsets&&(i+=a.offset().left-a.position().left),-1==w&&(w=i),g=a.css("position"),n=!0,-1!=b.options.bottom&&(a.trigger("preFixed"),q(),a.trigger("fixed")));var d=c(window).scrollLeft(),e=c(window).scrollTop(),
p=u();if(b.options.minWidth&&c(window).width()<b.options.minWidth){if(f()||k()||!m)j(),a.trigger("preUnfixed"),h(),a.trigger("unfixed")}else if(-1==b.options.bottom)if(0<p&&e>=p-b.options.marginTop){if(!k()||!m)j(),a.trigger("preAbsolute"),a.css({width:a.width(),position:"absolute",top:u(),left:i}),g="absolute",a.trigger("unfixed")}else if(e>=v-b.options.marginTop){if(!f()||!m)j(),a.trigger("preFixed"),q(),l=-1,a.trigger("fixed");r(d)}else{if(f()||k()||!m)j(),a.trigger("preUnfixed"),h(),a.trigger("unfixed")}else 0<
p?e+c(window).height()-a.outerHeight(!0)>=p-b.options.marginTop?f()&&(j(),a.trigger("preUnfixed"),h(),a.trigger("unfixed")):(f()||(j(),a.trigger("preFixed"),q()),r(d),a.trigger("fixed")):r(d)}}function j(){var b=a.css("position");"absolute"==b?a.trigger("postAbsolute"):"fixed"==b?a.trigger("postFixed"):a.trigger("postUnfixed")}var b=this;b.$el=c(d);b.el=d;b.$el.data("ScrollToFixed",b);var n=!1,a=b.$el,g,v=0,i=0,w=-1,l=-1,e=null,t=function(){a.is(":visible")&&(n=!1,s())},x=function(){s()};b.init=function(){b.options=
c.extend({},c.ScrollToFixed.defaultOptions,y);if(!("iPad"===navigator.platform||"iPhone"===navigator.platform||"iPod"===navigator.platform)||navigator.userAgent.match(/OS 5_.*\ like Mac OS X/i))b.$el.css("z-index",b.options.zIndex),e=c("<div />"),g=a.css("position"),!f()&&!k()&&b.$el.after(e),c(window).bind("resize.ScrollToFixed",t),c(window).bind("scroll.ScrollToFixed",x),b.options.preFixed&&a.bind("preFixed.ScrollToFixed",b.options.preFixed),b.options.postFixed&&a.bind("postFixed.ScrollToFixed",
b.options.postFixed),b.options.preUnfixed&&a.bind("preUnfixed.ScrollToFixed",b.options.preUnfixed),b.options.postUnfixed&&a.bind("postUnfixed.ScrollToFixed",b.options.postUnfixed),b.options.preAbsolute&&a.bind("preAbsolute.ScrollToFixed",b.options.preAbsolute),b.options.postAbsolute&&a.bind("postAbsolute.ScrollToFixed",b.options.postAbsolute),b.options.fixed&&a.bind("fixed.ScrollToFixed",b.options.fixed),b.options.unfixed&&a.bind("unfixed.ScrollToFixed",b.options.unfixed),b.options.spacerClass&&e.addClass(b.options.spacerClass),
a.bind("resize.ScrollToFixed",function(){e.height(a.height())}),a.bind("scroll.ScrollToFixed",function(){a.trigger("preUnfixed");h();a.trigger("unfixed");s()}),a.bind("remove.ScrollToFixed",function(){a.trigger("preUnfixed");h();a.trigger("unfixed");c(window).unbind("resize.ScrollToFixed",t);c(window).unbind("scroll.ScrollToFixed",x);a.unbind(".ScrollToFixed");b.$el.removeData("ScrollToFixed")}),t()};b.init()};c.ScrollToFixed.defaultOptions={marginTop:0,limit:0,bottom:-1,zIndex:1E3};c.fn.scrollToFixed=
function(d){return this.each(function(){new c.ScrollToFixed(this,d)})}})(jQuery);
(function(e){"undefined"==typeof e.fn.each2&&e.fn.extend({each2:function(g){for(var i=e([0]),m=-1,t=this.length;++m<t&&(i.context=i[0]=this[m])&&!1!==g.call(i[0],m,i););return this}})})(jQuery);
(function(e,g){function i(a,b){var c=0,d=b.length,j;if("undefined"===typeof a)return-1;if(a.constructor===String)for(;c<d;c+=1){if(0===a.localeCompare(b[c]))return c}else for(;c<d;c+=1)if(j=b[c],j.constructor===String){if(0===j.localeCompare(a))return c}else if(j===a)return c;return-1}function m(a,b){return a===b?!0:a===g||b===g||null===a||null===b?!1:a.constructor===String?0===a.localeCompare(b):b.constructor===String?0===b.localeCompare(a):!1}function t(a,b){var c,d,j;if(null===a||1>a.length)return[];
c=a.split(b);d=0;for(j=c.length;d<j;d+=1)c[d]=e.trim(c[d]);return c}function B(a,b,c){var c=c||g,d;return function(){var j=arguments;window.clearTimeout(d);d=window.setTimeout(function(){b.apply(c,j)},a)}}function l(a){a.preventDefault();a.stopPropagation()}function C(a,b,c){var d=a.toUpperCase().indexOf(b.toUpperCase()),b=b.length;0>d?c.push(a):(c.push(a.substring(0,d)),c.push("<span class='select2-match'>"),c.push(a.substring(d,d+b)),c.push("</span>"),c.push(a.substring(d+b,a.length)))}function D(a){var b,
c=0,d=null,j=a.quietMillis||100;return function(h){window.clearTimeout(b);b=window.setTimeout(function(){var b=c+=1,j=a.data,n=a.transport||e.ajax,f=a.traditional||!1,g=a.type||"GET",j=j.call(this,h.term,h.page,h.context);null!==d&&d.abort();d=n.call(null,{url:a.url,dataType:a.dataType,data:j,type:g,traditional:f,success:function(d){b<c||(d=a.results(d,h.page),h.callback(d))}})},j)}}function E(a){var b=a,c,d=function(a){return""+a.text};e.isArray(b)||(d=b.text,e.isFunction(d)||(c=b.text,d=function(a){return a[c]}),
b=b.results);return function(a){var c=a.term,f={results:[]},k;""===c?a.callback({results:b}):(k=function(b,f){var g,u,b=b[0];if(b.children){g={};for(u in b)b.hasOwnProperty(u)&&(g[u]=b[u]);g.children=[];e(b.children).each2(function(a,b){k(b,g.children)});g.children.length&&f.push(g)}else a.matcher(c,d(b))&&f.push(b)},e(b).each2(function(a,b){k(b,f.results)}),a.callback(f))}}function F(a){return e.isFunction(a)?a:function(b){var c=b.term,d={results:[]};e(a).each(function(){var a=this.text!==g,e=a?
this.text:this;if(""===c||b.matcher(c,e))d.results.push(a?this:{id:this,text:this})});b.callback(d)}}function v(a){if(e.isFunction(a))return!0;if(!a)return!1;throw Error("formatterName must be a function or a falsy value");}function w(a){return e.isFunction(a)?a():a}function G(a){var b=0;e.each(a,function(a,d){d.children?b+=G(d.children):b++});return b}function I(a,b,c,d){var e=a,h=!1,f,k,n,p;if(!d.createSearchChoice||!d.tokenSeparators||1>d.tokenSeparators.length)return g;for(;;){h=-1;k=0;for(n=
d.tokenSeparators.length;k<n&&!(p=d.tokenSeparators[k],h=a.indexOf(p),0<=h);k++);if(0>h)break;f=a.substring(0,h);a=a.substring(h+p.length);if(0<f.length&&(f=d.createSearchChoice(f,b),f!==g&&null!==f&&d.id(f)!==g&&null!==d.id(f))){h=!1;k=0;for(n=b.length;k<n;k++)if(m(d.id(f),d.id(b[k]))){h=!0;break}h||c(f)}}if(0!=e.localeCompare(a))return a}function y(a,b){var c=function(){};c.prototype=new a;c.prototype.constructor=c;c.prototype.parent=a.prototype;c.prototype=e.extend(c.prototype,b);return c}if(window.Select2===
g){var f,x,z,A,H,r;f={TAB:9,ENTER:13,ESC:27,SPACE:32,LEFT:37,UP:38,RIGHT:39,DOWN:40,SHIFT:16,CTRL:17,ALT:18,PAGE_UP:33,PAGE_DOWN:34,HOME:36,END:35,BACKSPACE:8,DELETE:46,isArrow:function(a){a=a.which?a.which:a;switch(a){case f.LEFT:case f.RIGHT:case f.UP:case f.DOWN:return!0}return!1},isControl:function(a){switch(a.which){case f.SHIFT:case f.CTRL:case f.ALT:return!0}return a.metaKey?!0:!1},isFunctionKey:function(a){a=a.which?a.which:a;return 112<=a&&123>=a}};var J=1;H=function(){return J++};e(document).delegate("body",
"mousemove",function(a){e.data(document,"select2-lastpos",{x:a.pageX,y:a.pageY})});e(document).ready(function(){e(document).delegate("body","mousedown touchend",function(a){var b=e(a.target).closest("div.select2-container").get(0),c;b?e(document).find("div.select2-container-active").each(function(){this!==b&&e(this).data("select2").blur()}):(b=e(a.target).closest("div.select2-drop").get(0),e(document).find("div.select2-drop-active").each(function(){this!==b&&e(this).data("select2").blur()}));b=e(a.target);
c=b.attr("for");"LABEL"===a.target.tagName&&c&&0<c.length&&(b=e("#"+c),b=b.data("select2"),b!==g&&(b.focus(),a.preventDefault()))})});x=y(Object,{bind:function(a){var b=this;return function(){a.apply(b,arguments)}},init:function(a){var b,c;this.opts=a=this.prepareOpts(a);this.id=a.id;a.element.data("select2")!==g&&null!==a.element.data("select2")&&this.destroy();this.enabled=!0;this.container=this.createContainer();this.containerId="s2id_"+(a.element.attr("id")||"autogen"+H());this.containerSelector=
"#"+this.containerId.replace(/([;&,\.\+\*\~':"\!\^#$%@\[\]\(\)=>\|])/g,"\\$1");this.container.attr("id",this.containerId);var d=!1,j;this.body=function(){!1===d&&(j=a.element.closest("body"),d=!0);return j};a.element.attr("class")!==g&&this.container.addClass(a.element.attr("class").replace(/validate\[[\S ]+] ?/,""));this.container.css(w(a.containerCss));this.container.addClass(w(a.containerCssClass));this.opts.element.data("select2",this).hide().before(this.container);this.container.data("select2",
this);this.dropdown=this.container.find(".select2-drop");this.dropdown.addClass(w(a.dropdownCssClass));this.dropdown.data("select2",this);this.results=b=this.container.find(".select2-results");this.search=c=this.container.find("input.select2-input");c.attr("tabIndex",this.opts.element.attr("tabIndex"));this.resultsPage=0;this.context=null;this.initContainer();this.initContainerWidth();this.results.bind("mousemove",function(a){var b=e.data(document,"select2-lastpos");(b===g||b.x!==a.pageX||b.y!==a.pageY)&&
e(a.target).trigger("mousemove-filtered",a)});this.dropdown.delegate(".select2-results","mousemove-filtered",this.bind(this.highlightUnderEvent));var h=this.results,f=B(80,function(a){h.trigger("scroll-debounced",a)});h.bind("scroll",function(a){0<=i(a.target,h.get())&&f(a)});this.dropdown.delegate(".select2-results","scroll-debounced",this.bind(this.loadMoreIfNeeded));e.fn.mousewheel&&b.mousewheel(function(a,c,d,e){c=b.scrollTop();0<e&&0>=c-e?(b.scrollTop(0),l(a)):0>e&&b.get(0).scrollHeight-b.scrollTop()+
e<=b.height()&&(b.scrollTop(b.get(0).scrollHeight-b.height()),l(a))});c.bind("keydown",function(){e.data(c,"keyup-change-value")===g&&e.data(c,"keyup-change-value",c.val())});c.bind("keyup",function(){var a=e.data(c,"keyup-change-value");a!==g&&c.val()!==a&&(e.removeData(c,"keyup-change-value"),c.trigger("keyup-change"))});c.bind("keyup-change",this.bind(this.updateResults));c.bind("focus",function(){c.addClass("select2-focused");" "===c.val()&&c.val("")});c.bind("blur",function(){c.removeClass("select2-focused")});
this.dropdown.delegate(".select2-results","mouseup",this.bind(function(a){0<e(a.target).closest(".select2-result-selectable:not(.select2-disabled)").length?(this.highlightUnderEvent(a),this.selectHighlighted(a)):this.focusSearch();l(a)}));this.dropdown.bind("click mouseup mousedown",function(a){a.stopPropagation()});e.isFunction(this.opts.initSelection)&&(this.initSelection(),this.monitorSource());(a.element.is(":disabled")||a.element.is("[readonly='readonly']"))&&this.disable()},destroy:function(){var a=
this.opts.element.data("select2");a!==g&&(a.container.remove(),a.dropdown.remove(),a.opts.element.removeData("select2").unbind(".select2").show())},prepareOpts:function(a){var b,c,d;b=a.element;"select"===b.get(0).tagName.toLowerCase()&&(this.select=c=a.element);c&&e.each("id multiple ajax query createSearchChoice initSelection data tags".split(" "),function(){if(this in a)throw Error("Option '"+this+"' is not allowed for Select2 when attached to a <select> element.");});a=e.extend({},{populateResults:function(b,
c,d){var f,n=this.opts.id,p=this;f=function(b,c,j){var h,l,i,m,s,q,r;h=0;for(l=b.length;h<l;h+=1)i=b[h],m=n(i)!==g,s=i.children&&0<i.children.length,q=e("<li></li>"),q.addClass("select2-results-dept-"+j),q.addClass("select2-result"),q.addClass(m?"select2-result-selectable":"select2-result-unselectable"),s&&q.addClass("select2-result-with-children"),q.addClass(p.opts.formatResultCssClass(i)),m=e("<div></div>"),m.addClass("select2-result-label"),r=a.formatResult(i,m,d),r!==g&&m.html(p.opts.escapeMarkup(r)),
q.append(m),s&&(s=e("<ul></ul>"),s.addClass("select2-result-sub"),f(i.children,s,j+1),q.append(s)),q.data("select2-data",i),c.append(q)};f(c,b,0)}},e.fn.select2.defaults,a);"function"!==typeof a.id&&(d=a.id,a.id=function(a){return a[d]});if(c)a.query=this.bind(function(a){var c={results:[],more:!1},d=a.term,f,n,p;p=function(b,c){var e;b.is("option")?a.matcher(d,b.text(),b)&&c.push({id:b.attr("value"),text:b.text(),element:b.get(),css:b.attr("class")}):b.is("optgroup")&&(e={text:b.attr("label"),children:[],
element:b.get(),css:b.attr("class")},b.children().each2(function(a,b){p(b,e.children)}),0<e.children.length&&c.push(e))};f=b.children();this.getPlaceholder()!==g&&0<f.length&&(n=f[0],""===e(n).text()&&(f=f.not(n)));f.each2(function(a,b){p(b,c.results)});a.callback(c)}),a.id=function(a){return a.id},a.formatResultCssClass=function(a){return a.css};else if(!("query"in a))if("ajax"in a){if((c=a.element.data("ajax-url"))&&0<c.length)a.ajax.url=c;a.query=D(a.ajax)}else"data"in a?a.query=E(a.data):"tags"in
a&&(a.query=F(a.tags),a.createSearchChoice=function(a){return{id:a,text:a}},a.initSelection=function(b,c){var d=[];e(t(b.val(),a.separator)).each(function(){var b=this,c=this,j=a.tags;e.isFunction(j)&&(j=j());e(j).each(function(){if(m(this.id,b))return c=this.text,!1});d.push({id:b,text:c})});c(d)});if("function"!==typeof a.query)throw"query function not defined for Select2 "+a.element.attr("id");return a},monitorSource:function(){this.opts.element.bind("change.select2",this.bind(function(){!0!==
this.opts.element.data("select2-change-triggered")&&this.initSelection()}))},triggerChange:function(a){a=a||{};a=e.extend({},a,{type:"change",val:this.val()});this.opts.element.data("select2-change-triggered",!0);this.opts.element.trigger(a);this.opts.element.data("select2-change-triggered",!1);this.opts.element.click();this.opts.blurOnChange&&this.opts.element.blur()},enable:function(){this.enabled||(this.enabled=!0,this.container.removeClass("select2-container-disabled"))},disable:function(){this.enabled&&
(this.close(),this.enabled=!1,this.container.addClass("select2-container-disabled"))},opened:function(){return this.container.hasClass("select2-dropdown-open")},positionDropdown:function(){var a=this.container.offset(),b=this.container.outerHeight(),c=this.container.outerWidth(),d=this.dropdown.outerHeight(),j=e(window).scrollTop()+document.documentElement.clientHeight,b=a.top+b,f=a.left,j=b+d<=j,g=a.top-d>=this.body().scrollTop(),k=this.dropdown.hasClass("select2-drop-above"),n;"static"!==this.body().css("position")&&
(n=this.body().offset(),b-=n.top,f-=n.left);k?(k=!0,!g&&j&&(k=!1)):(k=!1,!j&&g&&(k=!0));k?(b=a.top-d,this.container.addClass("select2-drop-above"),this.dropdown.addClass("select2-drop-above")):(this.container.removeClass("select2-drop-above"),this.dropdown.removeClass("select2-drop-above"));a=e.extend({top:b,left:f,width:c},w(this.opts.dropdownCss));this.dropdown.css(a)},shouldOpen:function(){var a;if(this.opened())return!1;a=e.Event("open");this.opts.element.trigger(a);return!a.isDefaultPrevented()},
clearDropdownAlignmentPreference:function(){this.container.removeClass("select2-drop-above");this.dropdown.removeClass("select2-drop-above")},open:function(){if(!this.shouldOpen())return!1;window.setTimeout(this.bind(this.opening),1);return!0},opening:function(){var a=this.containerId,b=this.containerSelector,c="scroll."+a,d="resize."+a;this.container.parents().each(function(){e(this).bind(c,function(){var a=e(b);0==a.length&&e(this).unbind(c);a.select2("close")})});e(window).bind(d,function(){var a=
e(b);0==a.length&&e(window).unbind(d);a.select2("close")});this.clearDropdownAlignmentPreference();" "===this.search.val()&&this.search.val("");this.container.addClass("select2-dropdown-open").addClass("select2-container-active");this.updateResults(!0);this.dropdown[0]!==this.body().children().last()[0]&&this.dropdown.detach().appendTo(this.body());this.dropdown.show();this.positionDropdown();this.dropdown.addClass("select2-drop-active");this.ensureHighlightVisible();this.focusSearch()},close:function(){if(this.opened()){var a=
this;this.container.parents().each(function(){e(this).unbind("scroll."+a.containerId)});e(window).unbind("resize."+this.containerId);this.clearDropdownAlignmentPreference();this.dropdown.hide();this.container.removeClass("select2-dropdown-open").removeClass("select2-container-active");this.results.empty();this.clearSearch();this.opts.element.trigger(e.Event("close"))}},clearSearch:function(){},ensureHighlightVisible:function(){var a=this.results,b,c,d,f;c=this.highlight();0>c||(0==c?a.scrollTop(0):
(b=a.find(".select2-result-selectable"),d=e(b[c]),f=d.offset().top+d.outerHeight(),c===b.length-1&&(b=a.find("li.select2-more-results"),0<b.length&&(f=b.offset().top+b.outerHeight())),b=a.offset().top+a.outerHeight(),f>b&&a.scrollTop(a.scrollTop()+(f-b)),d=d.offset().top-a.offset().top,0>d&&a.scrollTop(a.scrollTop()+d)))},moveHighlight:function(a){for(var b=this.results.find(".select2-result-selectable"),c=this.highlight();-1<c&&c<b.length;){var c=c+a,d=e(b[c]);if(d.hasClass("select2-result-selectable")&&
!d.hasClass("select2-disabled")){this.highlight(c);break}}},highlight:function(a){var b=this.results.find(".select2-result-selectable").not(".select2-disabled");if(0===arguments.length)return i(b.filter(".select2-highlighted")[0],b.get());a>=b.length&&(a=b.length-1);0>a&&(a=0);b.removeClass("select2-highlighted");e(b[a]).addClass("select2-highlighted");this.ensureHighlightVisible()},countSelectableResults:function(){return this.results.find(".select2-result-selectable").not(".select2-disabled").length},
highlightUnderEvent:function(a){a=e(a.target).closest(".select2-result-selectable");if(0<a.length&&!a.is(".select2-highlighted")){var b=this.results.find(".select2-result-selectable");this.highlight(b.index(a))}else 0==a.length&&this.results.find(".select2-highlighted").removeClass("select2-highlighted")},loadMoreIfNeeded:function(){var a=this.results,b=a.find("li.select2-more-results"),c,d=this.resultsPage+1,e=this,f=this.search.val(),g=this.context;0!==b.length&&(c=b.offset().top-a.offset().top-
a.height(),0>=c&&(b.addClass("select2-active"),this.opts.query({term:f,page:d,context:g,matcher:this.opts.matcher,callback:this.bind(function(c){e.opened()&&(e.opts.populateResults.call(this,a,c.results,{term:f,page:d,context:g}),!0===c.more?(b.detach().appendTo(a).text(e.opts.formatLoadMore(d+1)),window.setTimeout(function(){e.loadMoreIfNeeded()},10)):b.remove(),e.positionDropdown(),e.resultsPage=d)})})))},tokenize:function(){},updateResults:function(a){function b(){f.scrollTop(0);d.removeClass("select2-active");
k.positionDropdown()}function c(a){f.html(k.opts.escapeMarkup(a));b()}var d=this.search,f=this.results,h=this.opts,i,k=this;!0!==a&&(!1===this.showSearchInput||!this.opened())||(d.addClass("select2-active"),1<=h.maximumSelectionSize&&(i=this.data(),e.isArray(i)&&i.length>=h.maximumSelectionSize&&v(h.formatSelectionTooBig,"formatSelectionTooBig"))?c("<li class='select2-selection-limit'>"+h.formatSelectionTooBig(h.maximumSelectionSize)+"</li>"):d.val().length<h.minimumInputLength&&v(h.formatInputTooShort,
"formatInputTooShort")?c("<li class='select2-no-results'>"+h.formatInputTooShort(d.val(),h.minimumInputLength)+"</li>"):(c("<li class='select2-searching'>"+h.formatSearching()+"</li>"),i=this.tokenize(),i!=g&&null!=i&&d.val(i),this.resultsPage=1,h.query({term:d.val(),page:this.resultsPage,context:null,matcher:h.matcher,callback:this.bind(function(i){var l;this.opened()&&((this.context=i.context===g?null:i.context,this.opts.createSearchChoice&&""!==d.val()&&(l=this.opts.createSearchChoice.call(null,
d.val(),i.results),l!==g&&null!==l&&k.id(l)!==g&&null!==k.id(l)&&0===e(i.results).filter(function(){return m(k.id(this),k.id(l))}).length&&i.results.unshift(l)),0===i.results.length&&v(h.formatNoMatches,"formatNoMatches"))?c("<li class='select2-no-results'>"+h.formatNoMatches(d.val())+"</li>"):(f.empty(),k.opts.populateResults.call(this,f,i.results,{term:d.val(),page:this.resultsPage,context:null}),!0===i.more&&v(h.formatLoadMore,"formatLoadMore")&&(f.append("<li class='select2-more-results'>"+k.opts.escapeMarkup(h.formatLoadMore(this.resultsPage))+
"</li>"),window.setTimeout(function(){k.loadMoreIfNeeded()},10)),this.postprocessResults(i,a),b()))})})))},cancel:function(){this.close()},blur:function(){this.close();this.container.removeClass("select2-container-active");this.dropdown.removeClass("select2-drop-active");this.search[0]===document.activeElement&&this.search.blur();this.clearSearch();this.selection.find(".select2-search-choice-focus").removeClass("select2-search-choice-focus")},focusSearch:function(){this.search.show();this.search.focus();
window.setTimeout(this.bind(function(){this.search.show();this.search.focus();this.search.val(this.search.val())}),10)},selectHighlighted:function(){var a=this.highlight(),b=this.results.find(".select2-highlighted").not(".select2-disabled"),c=b.closest(".select2-result-selectable").data("select2-data");c&&(b.addClass("select2-disabled"),this.highlight(a),this.onSelect(c))},getPlaceholder:function(){return this.opts.element.attr("placeholder")||this.opts.element.attr("data-placeholder")||this.opts.element.data("placeholder")||
this.opts.placeholder},initContainerWidth:function(){var a=function(){var a,c,d,f;if("off"===this.opts.width)return null;if("element"===this.opts.width)return 0===this.opts.element.outerWidth()?"auto":this.opts.element.outerWidth()+"px";if("copy"===this.opts.width||"resolve"===this.opts.width){a=this.opts.element.attr("style");if(a!==g){a=a.split(";");d=0;for(f=a.length;d<f;d+=1)if(c=a[d].replace(/\s/g,"").match(/width:(([-+]?([0-9]*\.)?[0-9]+)(px|em|ex|%|in|cm|mm|pt|pc))/),null!==c&&1<=c.length)return c[1]}return"resolve"===
this.opts.width?(a=this.opts.element.css("width"),0<a.indexOf("%")?a:0===this.opts.element.outerWidth()?"auto":this.opts.element.outerWidth()+"px"):null}return e.isFunction(this.opts.width)?this.opts.width():this.opts.width}.call(this);null!==a&&this.container.attr("style","width: "+a)}});z=y(x,{createContainer:function(){return e("<div></div>",{"class":"select2-container"}).html("    <a href='#' onclick='return false;' class='select2-choice'>   <span></span><abbr class='select2-search-choice-close' style='display:none;'></abbr>   <div><b></b></div></a>    <div class='select2-drop select2-offscreen'>   <div class='select2-search'>       <input type='text' autocomplete='off' class='select2-input'/>   </div>   <ul class='select2-results'>   </ul></div>")},
opening:function(){this.search.show();this.parent.opening.apply(this,arguments);this.dropdown.removeClass("select2-offscreen")},close:function(){this.opened()&&(this.parent.close.apply(this,arguments),this.dropdown.removeAttr("style").addClass("select2-offscreen").insertAfter(this.selection).show())},focus:function(){this.close();this.selection.focus()},isFocused:function(){return this.selection[0]===document.activeElement},cancel:function(){this.parent.cancel.apply(this,arguments);this.selection.focus()},
initContainer:function(){var a,b=this.dropdown;this.selection=a=this.container.find(".select2-choice");this.search.bind("keydown",this.bind(function(a){if(this.enabled)if(a.which===f.PAGE_UP||a.which===f.PAGE_DOWN)l(a);else if(this.opened())switch(a.which){case f.UP:case f.DOWN:this.moveHighlight(a.which===f.UP?-1:1);l(a);break;case f.TAB:case f.ENTER:this.selectHighlighted();l(a);break;case f.ESC:this.cancel(a),l(a)}else a.which===f.TAB||f.isControl(a)||f.isFunctionKey(a)||a.which===f.ESC||!1===
this.opts.openOnEnter&&a.which===f.ENTER||this.open()}));this.search.bind("focus",this.bind(function(){this.selection.attr("tabIndex","-1")}));this.search.bind("blur",this.bind(function(){this.opened()||this.container.removeClass("select2-container-active");window.setTimeout(this.bind(function(){this.selection.attr("tabIndex",this.opts.element.attr("tabIndex"))}),10)}));a.bind("mousedown",this.bind(function(){this.opened()?(this.close(),this.selection.focus()):this.enabled&&this.open()}));b.bind("mousedown",
this.bind(function(){this.search.focus()}));a.bind("focus",this.bind(function(){this.container.addClass("select2-container-active");this.search.attr("tabIndex","-1")}));a.bind("blur",this.bind(function(){this.opened()||this.container.removeClass("select2-container-active");window.setTimeout(this.bind(function(){this.search.attr("tabIndex",this.opts.element.attr("tabIndex"))}),10)}));a.bind("keydown",this.bind(function(a){if(this.enabled)if(a.which===f.PAGE_UP||a.which===f.PAGE_DOWN)l(a);else if(!(a.which===
f.TAB||f.isControl(a)||f.isFunctionKey(a)||a.which===f.ESC)&&!(!1===this.opts.openOnEnter&&a.which===f.ENTER))if(a.which==f.DELETE)this.opts.allowClear&&this.clear();else{this.open();if(a.which!==f.ENTER&&!(48>a.which)){var b=String.fromCharCode(a.which).toLowerCase();a.shiftKey&&(b=b.toUpperCase());this.search.focus();this.search.val(b)}l(a)}}));a.delegate("abbr","mousedown",this.bind(function(a){this.enabled&&(this.clear(),l(a),this.close(),this.triggerChange(),this.selection.focus())}));this.setPlaceholder();
this.search.bind("focus",this.bind(function(){this.container.addClass("select2-container-active")}))},clear:function(){this.opts.element.val("");this.selection.find("span").empty();this.selection.removeData("select2-data");this.setPlaceholder()},initSelection:function(){if(""===this.opts.element.val())this.close(),this.setPlaceholder();else{var a=this;this.opts.initSelection.call(null,this.opts.element,function(b){b!==g&&null!==b&&(a.updateSelection(b),a.close(),a.setPlaceholder())})}},prepareOpts:function(){var a=
this.parent.prepareOpts.apply(this,arguments);"select"===a.element.get(0).tagName.toLowerCase()&&(a.initSelection=function(a,c){var d=a.find(":selected");e.isFunction(c)&&c({id:d.attr("value"),text:d.text()})});return a},setPlaceholder:function(){var a=this.getPlaceholder();""===this.opts.element.val()&&a!==g&&!(this.select&&""!==this.select.find("option:first").text())&&(this.selection.find("span").html(this.opts.escapeMarkup(a)),this.selection.addClass("select2-default"),this.selection.find("abbr").hide())},
postprocessResults:function(a,b){var c=0,d=this,f=!0;this.results.find(".select2-result-selectable").each2(function(a,b){if(m(d.id(b.data("select2-data")),d.opts.element.val()))return c=a,!1});this.highlight(c);!0===b&&(f=this.showSearchInput=G(a.results)>=this.opts.minimumResultsForSearch,this.dropdown.find(".select2-search")[f?"removeClass":"addClass"]("select2-search-hidden"),e(this.dropdown,this.container)[f?"addClass":"removeClass"]("select2-with-searchbox"))},onSelect:function(a){var b=this.opts.element.val();
this.opts.element.val(this.id(a));this.updateSelection(a);this.close();this.selection.focus();m(b,this.id(a))||this.triggerChange()},updateSelection:function(a){var b=this.selection.find("span");this.selection.data("select2-data",a);b.empty();a=this.opts.formatSelection(a,b);a!==g&&b.append(this.opts.escapeMarkup(a));this.selection.removeClass("select2-default");this.opts.allowClear&&this.getPlaceholder()!==g&&this.selection.find("abbr").show()},val:function(){var a,b=null,c=this;if(0===arguments.length)return this.opts.element.val();
a=arguments[0];if(this.select)this.select.val(a).find(":selected").each2(function(a,c){b={id:c.attr("value"),text:c.text()};return!1}),this.updateSelection(b),this.setPlaceholder();else{if(this.opts.initSelection===g)throw Error("cannot call val() if initSelection() is not defined");a?(this.opts.element.val(a),this.opts.initSelection(this.opts.element,function(a){c.opts.element.val(!a?"":c.id(a));c.updateSelection(a);c.setPlaceholder()})):this.clear()}},clearSearch:function(){this.search.val("")},
data:function(a){var b;if(0===arguments.length)return b=this.selection.data("select2-data"),b==g&&(b=null),b;!a||""===a?this.clear():(this.opts.element.val(!a?"":this.id(a)),this.updateSelection(a))}});A=y(x,{createContainer:function(){return e("<div></div>",{"class":"select2-container select2-container-multi"}).html("    <ul class='select2-choices'>  <li class='select2-search-field'>    <input type='text' autocomplete='off' class='select2-input'>  </li></ul><div class='select2-drop select2-drop-multi' style='display:none;'>   <ul class='select2-results'>   </ul></div>")},
prepareOpts:function(){var a=this.parent.prepareOpts.apply(this,arguments);"select"===a.element.get(0).tagName.toLowerCase()&&(a.initSelection=function(a,c){var d=[];a.find(":selected").each2(function(a,b){d.push({id:b.attr("value"),text:b.text()})});e.isFunction(c)&&c(d)});return a},initContainer:function(){var a;this.searchContainer=this.container.find(".select2-search-field");this.selection=a=this.container.find(".select2-choices");this.search.bind("keydown",this.bind(function(b){if(this.enabled){if(b.which===
f.BACKSPACE&&""===this.search.val()){this.close();var c;c=a.find(".select2-search-choice-focus");if(0<c.length){this.unselect(c.first());this.search.width(10);l(b);return}c=a.find(".select2-search-choice");0<c.length&&c.last().addClass("select2-search-choice-focus")}else a.find(".select2-search-choice-focus").removeClass("select2-search-choice-focus");if(this.opened())switch(b.which){case f.UP:case f.DOWN:this.moveHighlight(b.which===f.UP?-1:1);l(b);return;case f.ENTER:case f.TAB:this.selectHighlighted();
l(b);return;case f.ESC:this.cancel(b);l(b);return}if(!(b.which===f.TAB||f.isControl(b)||f.isFunctionKey(b)||b.which===f.BACKSPACE||b.which===f.ESC)&&!(!1===this.opts.openOnEnter&&b.which===f.ENTER))this.open(),(b.which===f.PAGE_UP||b.which===f.PAGE_DOWN)&&l(b)}}));this.search.bind("keyup",this.bind(this.resizeSearch));this.search.bind("blur",this.bind(function(a){this.container.removeClass("select2-container-active");this.search.removeClass("select2-focused");this.clearSearch();a.stopImmediatePropagation()}));
this.container.delegate(".select2-choices","mousedown",this.bind(function(a){this.enabled&&!(0<e(a.target).closest(".select2-search-choice").length)&&(this.clearPlaceholder(),this.open(),this.focusSearch(),a.preventDefault())}));this.container.delegate(".select2-choices","focus",this.bind(function(){this.enabled&&(this.container.addClass("select2-container-active"),this.dropdown.addClass("select2-drop-active"),this.clearPlaceholder())}));this.clearSearch()},enable:function(){this.enabled||(this.parent.enable.apply(this,
arguments),this.search.removeAttr("disabled"))},disable:function(){this.enabled&&(this.parent.disable.apply(this,arguments),this.search.attr("disabled",!0))},initSelection:function(){""===this.opts.element.val()&&(this.updateSelection([]),this.close(),this.clearSearch());if(this.select||""!==this.opts.element.val()){var a=this;this.opts.initSelection.call(null,this.opts.element,function(b){b!==g&&null!==b&&(a.updateSelection(b),a.close(),a.clearSearch())})}},clearSearch:function(){var a=this.getPlaceholder();
a!==g&&0===this.getVal().length&&!1===this.search.hasClass("select2-focused")?(this.search.val(a).addClass("select2-default"),this.resizeSearch()):this.search.val(" ").width(10)},clearPlaceholder:function(){this.search.hasClass("select2-default")?this.search.val("").removeClass("select2-default"):" "===this.search.val()&&this.search.val("")},opening:function(){this.parent.opening.apply(this,arguments);this.clearPlaceholder();this.resizeSearch();this.focusSearch()},close:function(){this.opened()&&
this.parent.close.apply(this,arguments)},focus:function(){this.close();this.search.focus()},isFocused:function(){return this.search.hasClass("select2-focused")},updateSelection:function(a){var b=[],c=[],d=this;e(a).each(function(){0>i(d.id(this),b)&&(b.push(d.id(this)),c.push(this))});a=c;this.selection.find(".select2-search-choice").remove();e(a).each(function(){d.addSelectedChoice(this)});d.postprocessResults()},tokenize:function(){var a=this.search.val(),a=this.opts.tokenizer(a,this.data(),this.bind(this.onSelect),
this.opts);null!=a&&a!=g&&(this.search.val(a),0<a.length&&this.open())},onSelect:function(a){this.addSelectedChoice(a);this.select&&this.postprocessResults();this.opts.closeOnSelect?(this.close(),this.search.width(10)):0<this.countSelectableResults()?(this.search.width(10),this.resizeSearch(),this.positionDropdown()):this.close();this.triggerChange({added:a});this.focusSearch()},cancel:function(){this.close();this.focusSearch()},addSelectedChoice:function(a){var b=e("<li class='select2-search-choice'>    <div></div>    <a href='#' onclick='return false;' class='select2-search-choice-close' tabindex='-1'></a></li>"),
c=this.id(a),d=this.getVal(),f;f=this.opts.formatSelection(a,b);b.find("div").replaceWith("<div>"+this.opts.escapeMarkup(f)+"</div>");b.find(".select2-search-choice-close").bind("mousedown",l).bind("click dblclick",this.bind(function(a){this.enabled&&(e(a.target).closest(".select2-search-choice").fadeOut("fast",this.bind(function(){this.unselect(e(a.target));this.selection.find(".select2-search-choice-focus").removeClass("select2-search-choice-focus");this.close();this.focusSearch()})).dequeue(),
l(a))})).bind("focus",this.bind(function(){this.enabled&&(this.container.addClass("select2-container-active"),this.dropdown.addClass("select2-drop-active"))}));b.data("select2-data",a);b.insertBefore(this.searchContainer);d.push(c);this.setVal(d)},unselect:function(a){var b=this.getVal(),c,d,a=a.closest(".select2-search-choice");if(0===a.length)throw"Invalid argument: "+a+". Must be .select2-search-choice";c=a.data("select2-data");d=i(this.id(c),b);0<=d&&(b.splice(d,1),this.setVal(b),this.select&&
this.postprocessResults());a.remove();this.triggerChange({removed:c})},postprocessResults:function(){var a=this.getVal(),b=this.results.find(".select2-result-selectable"),c=this.results.find(".select2-result-with-children"),d=this;b.each2(function(b,c){var e=d.id(c.data("select2-data"));0<=i(e,a)?c.addClass("select2-disabled").removeClass("select2-result-selectable"):c.removeClass("select2-disabled").addClass("select2-result-selectable")});c.each2(function(a,b){0==b.find(".select2-result-selectable").length?
b.addClass("select2-disabled"):b.removeClass("select2-disabled")});b.each2(function(a,b){if(!b.hasClass("select2-disabled")&&b.hasClass("select2-result-selectable"))return d.highlight(0),!1})},resizeSearch:function(){var a,b,c,d,f=this.search.outerWidth()-this.search.width();a=this.search;r||(c=a[0].currentStyle||window.getComputedStyle(a[0],null),r=e("<div></div>").css({position:"absolute",left:"-10000px",top:"-10000px",display:"none",fontSize:c.fontSize,fontFamily:c.fontFamily,fontStyle:c.fontStyle,
fontWeight:c.fontWeight,letterSpacing:c.letterSpacing,textTransform:c.textTransform,whiteSpace:"nowrap"}),e("body").append(r));r.text(a.val());a=r.width()+10;b=this.search.offset().left;c=this.selection.width();d=this.selection.offset().left;b=c-(b-d)-f;b<a&&(b=c-f);40>b&&(b=c-f);this.search.width(b)},getVal:function(){var a;if(this.select)return a=this.select.val(),null===a?[]:a;a=this.opts.element.val();return t(a,this.opts.separator)},setVal:function(a){var b;this.select?this.select.val(a):(b=
[],e(a).each(function(){0>i(this,b)&&b.push(this)}),this.opts.element.val(0===b.length?"":b.join(this.opts.separator)))},val:function(){var a,b=[],c=this;if(0===arguments.length)return this.getVal();if(a=arguments[0])if(this.setVal(a),this.select)this.select.find(":selected").each(function(){b.push({id:e(this).attr("value"),text:e(this).text()})}),this.updateSelection(b);else{if(this.opts.initSelection===g)throw Error("val() cannot be called if initSelection() is not defined");this.opts.initSelection(this.opts.element,
function(a){var b=e(a).map(c.id);c.setVal(b);c.updateSelection(a);c.clearSearch()})}else this.opts.element.val(""),this.updateSelection([]);this.clearSearch()},onSortStart:function(){if(this.select)throw Error("Sorting of elements is not supported when attached to <select>. Attach to <input type='hidden'/> instead.");this.search.width(0);this.searchContainer.hide()},onSortEnd:function(){var a=[],b=this;this.searchContainer.show();this.searchContainer.appendTo(this.searchContainer.parent());this.resizeSearch();
this.selection.find(".select2-search-choice").each(function(){a.push(b.opts.id(e(this).data("select2-data")))});this.setVal(a);this.triggerChange()},data:function(a){var b=this,c;if(0===arguments.length)return this.selection.find(".select2-search-choice").map(function(){return e(this).data("select2-data")}).get();a||(a=[]);c=e.map(a,function(a){return b.opts.id(a)});this.setVal(c);this.updateSelection(a);this.clearSearch()}});e.fn.select2=function(){var a=Array.prototype.slice.call(arguments,0),b,
c,d,f,h="val destroy opened open close focus isFocused container onSortStart onSortEnd enable disable positionDropdown data".split(" ");this.each(function(){if(0===a.length||"object"===typeof a[0])b=0===a.length?{}:e.extend({},a[0]),b.element=e(this),"select"===b.element.get(0).tagName.toLowerCase()?f=b.element.attr("multiple"):(f=b.multiple||!1,"tags"in b&&(b.multiple=f=!0)),c=f?new A:new z,c.init(b);else if("string"===typeof a[0]){if(0>i(a[0],h))throw"Unknown method: "+a[0];d=g;c=e(this).data("select2");
if(c!==g&&(d="container"===a[0]?c.container:c[a[0]].apply(c,a.slice(1)),d!==g))return!1}else throw"Invalid arguments to select2 plugin: "+a;});return d===g?this:d};e.fn.select2.defaults={width:"copy",closeOnSelect:!0,openOnEnter:!0,containerCss:{},dropdownCss:{},containerCssClass:"",dropdownCssClass:"",formatResult:function(a,b,c){b=[];C(a.text,c.term,b);return b.join("")},formatSelection:function(a){return a?a.text:g},formatResultCssClass:function(){return g},formatNoMatches:function(){return"No matches found"},
formatInputTooShort:function(a,b){return"Please enter "+(b-a.length)+" more characters"},formatSelectionTooBig:function(a){return"You can only select "+a+" item"+(1==a?"":"s")},formatLoadMore:function(){return"Loading more results..."},formatSearching:function(){return"Searching..."},minimumResultsForSearch:0,minimumInputLength:0,maximumSelectionSize:0,id:function(a){return a.id},matcher:function(a,b){return 0<=b.toUpperCase().indexOf(a.toUpperCase())},separator:",",tokenSeparators:[],tokenizer:I,
escapeMarkup:function(a){return a&&"string"===typeof a?a.replace(/&/g,"&amp;"):a},blurOnChange:!1};window.Select2={query:{ajax:D,local:E,tags:F},util:{debounce:B,markMatch:C},"class":{"abstract":x,single:z,multi:A}}}})(jQuery);